

name: Release on GitHub, CurseForge

on: [ workflow_dispatch ]

env:                                              
  MINECRAFT_VERSION: 1.20                       
  JAVA_VERSION: 17
  RELEASE_VERSION: 1.0.1
  RELEASE_NAME: rftl
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  PROJECT_ID: "888625"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           

permissions:
  contents: write

jobs:                                             
  build:                                          
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
         RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
         echo $RELEASE_VERSION
         echo ${{ steps.vars.outputs.tag }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Clean Project
        run: gradle clean

      - name: Build Project
        run: gradle build
        
      - name: Publish (CurseForge/GitHub)
        uses: Kir-Antipov/mc-publish@v3.2                                   
        with:
          curseforge-id: "${{ env.PROJECT_ID }}"
          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"
          
          github-tag: "v${{env.RELEASE_VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}-${{env.RELEASE_VERSION}}-${{env.MINECRAFT_VERSION}}"
          version: "${{env.RELEASE_VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md                                      

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"

