

name: Test Workflow

on: [ workflow_dispatch ]

env:                                              
  MINECRAFT_VERSION: 1.20                       
  JAVA_VERSION: 17      
  VERSION: 1.0.0+1.20
  RELEASE_NAME: rftl 1.0.0+1.20
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}           

permissions:
  contents: write

jobs:                                             
  build:                                          
    runs-on: ubuntu-latest                        
    steps:                                        
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set output
        id: vars
        run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT
      - name: Check output
        env:
          RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        run: |
          echo $RELEASE_VERSION
          echo ${{ steps.vars.outputs.tag }}

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Clean Project
        run: gradle clean

      - name: Build Project
        run: gradle build

      - name: Test Variables
        run: echo
#      - name: Publish (CurseForge/Modrinth/GitHub)
#        uses: Kir-Antipov/mc-publish@v3.2
#        with:
#          curseforge-id: 888625
#          curseforge-token: "${{env.CURSEFORGE_TOKEN}}"
#
#          github-tag: "v${{env.VERSION}}"
#          github-token: "${{env.GITHUB_TOKEN}}"
#
#          name: "${{env.RELEASE_NAME}}"
#          version: "${{env.VERSION}}"
#          version-type: release
#          changelog-file: CHANGELOG.md
#
#          loaders: fabric
#          game-versions: "${{env.MINECRAFT_VERSION}}"
#          java: "${{env.JAVA_VERSION}}"

